### ISSUE TITLE
Palm Loop outputs at different octaves

### ISSUE THREAD

**Issue by wiqid** [21kHz/21kHz-rack-plugins#1]
The fact that Palm Loop has outputs at different octaves is non-obvious and counter-intuitive. No offense, but I think this is a bad design decision.

If you do want to keep it this way, then I suggest putting the lower three outputs grouped together on a row at the bottom and clearly mark them as -1 or something like that, and the two "normal" frequency outputs grouped together on the row above them.

**Comment by jakehuryn** [comment]
yup, have had some other people mention this as well. i'm gonna keep the outputs as they are, for now at least, but i will definitely make it clearer what's what for the next update. i'll move them as you said and add pictures for the waveforms too, instead of the text.

the choice for octaves was really just a way for me to cheat and make the antialiasing process simpler. if i don't end up changing it for Palm Loop, any future oscillators will not feature this behavior.

thanks for the feedback!
